*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:39449 (IPv4)
Extension host agent listening on 39449

[21:58:14] 




[21:58:14] Extension host agent started.
[21:58:14] [127.0.0.1][39251563][ManagementConnection] New connection established.
[21:58:14] [127.0.0.1][71920de5][ExtensionHostConnection] New connection established.
[21:58:14] [127.0.0.1][71920de5][ExtensionHostConnection] <1242> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateIcon (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27763)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[21:58:17] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateIcon (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27763)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[21:58:17] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Got delay-shutdown request while in shutdown timeout, delaying
[21:59:24] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[21:59:24] Cancelling previous shutdown timeout
[21:59:24] [127.0.0.1][460f9477][ManagementConnection] New connection established.
[21:59:24] [127.0.0.1][938e2419][ExtensionHostConnection] New connection established.
[21:59:24] [127.0.0.1][938e2419][ExtensionHostConnection] <1400> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[21:59:27] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:00:05] [127.0.0.1][39251563][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:00:05] [127.0.0.1][71920de5][ExtensionHostConnection] <1242> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[22:00:05] Cancelling previous shutdown timeout
[22:23:22] [127.0.0.1][460f9477][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:23:22] [127.0.0.1][938e2419][ExtensionHostConnection] <1400> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[22:23:22] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[22:23:29] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[22:23:29] Cancelling previous shutdown timeout
[22:23:29] [127.0.0.1][bb874f5b][ManagementConnection] New connection established.
[22:23:29] [127.0.0.1][66adf9a8][ExtensionHostConnection] New connection established.
[22:23:29] [127.0.0.1][66adf9a8][ExtensionHostConnection] <1638> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:23:31] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Got delay-shutdown request while in shutdown timeout, delaying
[22:25:02] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[22:25:02] Cancelling previous shutdown timeout
[22:25:02] [127.0.0.1][ab301a21][ManagementConnection] New connection established.
[22:25:02] [127.0.0.1][84403b2d][ExtensionHostConnection] New connection established.
[22:25:02] [127.0.0.1][84403b2d][ExtensionHostConnection] <1786> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:25:05] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Got delay-shutdown request while in shutdown timeout, delaying
[22:25:46] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[22:25:46] Cancelling previous shutdown timeout
[22:25:47] [127.0.0.1][5f3cf88b][ManagementConnection] New connection established.
[22:25:47] [127.0.0.1][ab996507][ExtensionHostConnection] New connection established.
[22:25:47] [127.0.0.1][ab996507][ExtensionHostConnection] <1924> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:25:49] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:25:55] [127.0.0.1][5f3cf88b][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:25:55] [127.0.0.1][ab996507][ExtensionHostConnection] <1924> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[22:25:55] Cancelling previous shutdown timeout
[22:26:01] [127.0.0.1][8480a409][ManagementConnection] New connection established.
[22:26:01] [127.0.0.1][77bfa50c][ExtensionHostConnection] New connection established.
[22:26:01] [127.0.0.1][77bfa50c][ExtensionHostConnection] <2064> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:26:04] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:26:36] [127.0.0.1][8480a409][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:26:36] [127.0.0.1][77bfa50c][ExtensionHostConnection] <2064> Extension Host Process exited with code: 0, signal: null.
[22:26:41] [127.0.0.1][22d59279][ManagementConnection] New connection established.
[22:26:41] [127.0.0.1][c3e92b9a][ExtensionHostConnection] New connection established.
[22:26:41] [127.0.0.1][c3e92b9a][ExtensionHostConnection] <2231> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:26:43] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:26:45] [127.0.0.1][22d59279][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:26:45] [127.0.0.1][c3e92b9a][ExtensionHostConnection] <2231> Extension Host Process exited with code: 0, signal: null.
[22:26:54] [127.0.0.1][d55bfd49][ManagementConnection] New connection established.
[22:26:54] [127.0.0.1][46593869][ExtensionHostConnection] New connection established.
[22:26:54] [127.0.0.1][46593869][ExtensionHostConnection] <2383> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:26:56] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:29:44] [127.0.0.1][d55bfd49][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:29:44] [127.0.0.1][46593869][ExtensionHostConnection] <2383> Extension Host Process exited with code: 0, signal: null.
[22:29:47] [127.0.0.1][ab301a21][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:29:47] [127.0.0.1][84403b2d][ExtensionHostConnection] <1786> Extension Host Process exited with code: 0, signal: null.
[22:30:01] [127.0.0.1][c40ba6c1][ManagementConnection] New connection established.
[22:30:02] [127.0.0.1][be12cf22][ExtensionHostConnection] New connection established.
[22:30:02] [127.0.0.1][be12cf22][ExtensionHostConnection] <2551> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:30:04] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:34:07] [127.0.0.1][9ec74b3c][ManagementConnection] New connection established.
[22:34:07] [127.0.0.1][269d09ea][ExtensionHostConnection] New connection established.
[22:34:07] [127.0.0.1][269d09ea][ExtensionHostConnection] <2709> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:34:09] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[22:35:16] [127.0.0.1][bb874f5b][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:35:17] [127.0.0.1][66adf9a8][ExtensionHostConnection] <1638> Extension Host Process exited with code: 0, signal: null.
[22:50:07] [127.0.0.1][9ec74b3c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[22:50:08] [127.0.0.1][269d09ea][ExtensionHostConnection] <2709> Extension Host Process exited with code: 0, signal: null.
[23:08:16] [127.0.0.1][c40ba6c1][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[23:08:16] [127.0.0.1][be12cf22][ExtensionHostConnection] <2551> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[23:08:16] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[23:08:29] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[23:08:29] Cancelling previous shutdown timeout
[23:08:29] [127.0.0.1][054ddf8d][ManagementConnection] New connection established.
[23:08:30] [127.0.0.1][454465cf][ExtensionHostConnection] New connection established.
[23:08:30] [127.0.0.1][454465cf][ExtensionHostConnection] <3237> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[23:08:32] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
New EH opened, aborting shutdown
[23:13:29] New EH opened, aborting shutdown
[23:15:08] [127.0.0.1][054ddf8d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[23:15:08] [127.0.0.1][454465cf][ExtensionHostConnection] <3237> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[23:15:08] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[23:15:33] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[23:15:33] Cancelling previous shutdown timeout
[23:15:33] [127.0.0.1][b5835a81][ManagementConnection] New connection established.
[23:15:33] [127.0.0.1][8752c85d][ExtensionHostConnection] New connection established.
[23:15:33] [127.0.0.1][8752c85d][ExtensionHostConnection] <3490> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[23:15:35] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
New EH opened, aborting shutdown
[23:20:33] New EH opened, aborting shutdown
[23:30:11] [127.0.0.1][ee6eb114][ManagementConnection] New connection established.
[23:30:11] [127.0.0.1][f3690a98][ExtensionHostConnection] New connection established.
[23:30:11] [127.0.0.1][f3690a98][ExtensionHostConnection] <3673> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[23:30:14] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[23:31:05] [127.0.0.1][ee6eb114][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[23:31:05] [127.0.0.1][f3690a98][ExtensionHostConnection] <3673> Extension Host Process exited with code: 0, signal: null.
[23:31:12] [127.0.0.1][05a33d54][ManagementConnection] New connection established.
[23:31:12] [127.0.0.1][eb58fc57][ExtensionHostConnection] New connection established.
[23:31:12] [127.0.0.1][eb58fc57][ExtensionHostConnection] <3822> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[23:31:14] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/home/cesiaeli/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
